name: GDM Aircraft
favicon: null
layout_spectrum: 0.36124839819967747
typography_spectrum: 0.022567456122487783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.20238947519101202
  lightness: 0.047054498456418514
  saturation: 0.6703701557125896
  rhythmicContrast: 0.5814226281363517
purpose: []
